### ISSUE TITLE
Low FPS playback in v2

### ISSUE THREAD

**Issue by ghost** [ascora/LottieSharp#56]
When using a lottie animation using LottieSharp v2, I'm getting a low framerate playback, maybe 15fps or so. If i use the exact same Json file in winui 3 the playback is a smooth 30fps. Is there anything I'm doing wrong here?

- New WPF app
- Download https://assets4.lottiefiles.com/packages/lf20_b88nh30c.json
- Add LottieAnimationView and point to downloaded json file.

**Expected behavior**
Smooth playback

**Screenshots**
WPF (60 FPS GIF)
![Animation1](https://user-images.githubusercontent.com/76792853/188467876-4ace1900-2fdb-4ed5-9b4d-3ad155fd10ce.gif)

WinUI 3 (60 FPS GIF)
![Animation2](https://user-images.githubusercontent.com/76792853/188467913-39ce5b65-750d-4dd8-baf0-f35481a73089.gif)

**Comment by quicoli** [comment]
@xEsteem , could you please load your animation here: https://lottiefiles.com/editor
and see how does it perform and give me a feedback?

At my sight the WPF is running just like in the https://lottiefiles.com/editor

**Comment by ghost** [comment]
@quicoli In on the lottiefiles.com editor, it is running at 30fps, just as it does in winUI. It seems as though its just in WPF that its running at this reduced framerate

**Comment by quicoli** [comment]
@xEsteem I published a new version however I didn't touch anything regarding the player mechanism..  I loaded your animation on the https://lottiefiles.com/editor and played beside this new version. Have a look, see the video below, what you think?

https://recordit.co/EKmmEHGyCi

**Comment by ghost** [comment]
@quicoli I've updated to 2.0.1 but still see the same. I've actually been doing some experimentation, and I dont actually think that the issue is necessarily with this library. I tried using SkiaSharp directly, based on the [Uno Sample](https://github.com/unoplatform/Uno.Samples/blob/master/UI/SkottieSample/SkottieSample/SkottieSample.Shared/MainPage.xaml.cs), and it looks very similar to me than the results of LottieSharp, choppy playback, not smooth like web.

I did a bit of experimentation and I think using the `DispatcherTimer` doesn't really help things. Switching to a `System.Timers.Timer` and executing `InvalidateVisual` using `Dispatcher.BeginInvoke` actually made things a little better.

Another thing I tried that made things **much** smoother for me was doubling the refresh rate of the timer. I'm not too sure why, since in _theory_ that's just processing every frame twice..? But it helped a lot in the smoothness.

I've attached a zip file with the demo testing in here, see what it looks like your end. the first two are really choppy and not smooth really at all. The third is smoother, but still no where near as smooth as you get on web, or in winUI (example of which included in the zip too).
Check the WPF app out and see if you notice a difference between the 4. For me the first 3 seem very similar, but choppy, the 4th is much smoother, and the WinUI one is smoother still (more like what you get at https://lottiefiles.com/editor). 

[LottieTest.zip](https://github.com/quicoli/LottieSharp/files/9542535/LottieTest.zip)

UPDATE: I also tried `SkiaSharp.Skottie` in WinUI using `SkiaSharp.Views.WinUI`, and it looks just the same as it does in WPF, choppy when compared to the [lottie-windows](https://github.com/CommunityToolkit/Lottie-Windows) in winUI (i've updated the attached zip to include that), so I think we can close this issue tbh, because i think it falls outside of the scope of this package. The issue seems to be fundamental to the Skia.Skottie playback (perhaps specific to this machine i am using it on?).

**Comment by quicoli** [comment]
@xEsteem  thank you very much for all effort you have put on this issue. This week I'll dedicate time to analyze your code samples and if they improve LottieSharp, why not integrate it? I'll check it out this week. Thanks!
